# JSON data wrangling with python

Solving the double/multiple nesting problem

In [ ]:
import requests
import pandas as pd

In [ ]:
url ='https://api.worldbank.org/v2/country/GBR/indicator/SP.POP.TOTL?format=json'
html = requests.get(url)

In [ ]:
json_data = html.json()

In [ ]:
json_data[0]['page']

1

In [ ]:
json_data[1] #<- this is the data
good_data=json_data[1]

Creating a `pandas` dataframe

In [ ]:
#create dataframe directly
df=pd.DataFrame(good_data)

In [ ]:
df.head(5)

                                           indicator  ... decimal
0  {'id': 'SP.POP.TOTL', 'value': 'Population, to...  ...       0
1  {'id': 'SP.POP.TOTL', 'value': 'Population, to...  ...       0
2  {'id': 'SP.POP.TOTL', 'value': 'Population, to...  ...       0
3  {'id': 'SP.POP.TOTL', 'value': 'Population, to...  ...       0
4  {'id': 'SP.POP.TOTL', 'value': 'Population, to...  ...       0

[5 rows x 8 columns]

In [ ]:
df[  ['date','value']  ].to_excel('my_other_csv.xlsx')

In [ ]:
# create array in loop
for i in json_data[1]:
  # print(i)

SyntaxError: ignored

# Scraping *light*

Reading from `HTML` tables direclty with `pandas`

In [ ]:
pd.read_excel('my_other_csv.xlsx')

    Unnamed: 0  date     value
0            0  2020  67215293
1            1  2019  66836327
2            2  2018  66460344
3            3  2017  66058859
4            4  2016  65611593
5            5  2015  65116219
6            6  2014  64602298
7            7  2013  64128273
8            8  2012  63700215
9            9  2011  63258810
10          10  2010  62766365
11          11  2009  62276270
12          12  2008  61806995
13          13  2007  61322463
14          14  2006  60846820
15          15  2005  60401206
16          16  2004  59987905
17          17  2003  59647577
18          18  2002  59370479
19          19  2001  59119673
20          20  2000  58892514
21          21  1999  58682466
22          22  1998  58487141
23          23  1997  58316954
24          24  1996  58166950
25          25  1995  58019030
26          26  1994  57865745
27          27  1993  57718614
28          28  1992  57580402
29          29  1991  57424897
30          30  1990  57247586
31          31  1989  57076711
32          32  1988  56928327
33          33  1987  56802050
34          34  1986  56681396
35          35  1985  56550268
36          36  1984  56422072
37          37  1983  56332848
38          38  1982  56313641
39          39  1981  56333829
40          40  1980  56314216
41          41  1979  56246951
42          42  1978  56196504
43          43  1977  56193492
44          44  1976  56211968
45          45  1975  56225800
46          46  1974  56229974
47          47  1973  56194527
48          48  1972  56086065
49          49  1971  55896223

In [ ]:
tables=pd.read_html('https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(PPP)_per_capita')

In [ ]:
df=tables[1]

In [ ]:
df.head(5)

  Country (or territory)           Subregion  Region  ... World Bank[6]    CIA[7]
  Country (or territory)           Subregion  Region  ...          Year  Estimate    Year
0        Liechtenstein *      Western Europe  Europe  ...           NaN  139100.0  2009.0
1           Luxembourg *      Western Europe  Europe  ...        2020.0  114482.0  2019.0
2               Monaco *      Western Europe  Europe  ...           NaN  115700.0  2015.0
3            Singapore *  South-eastern Asia    Asia  ...        2020.0   97341.0  2019.0
4              Ireland *     Northern Europe  Europe  ...        2020.0   86781.0  2019.0

[5 rows x 9 columns]

In [ ]:
df.columns=['country','subregion','region','IMF','IMFyear','WB','WByear','CIA','CIAyear']

In [ ]:
df.head(5)

           country           subregion  region  ...  WByear       CIA  CIAyear
0  Liechtenstein *      Western Europe  Europe  ...     NaN  139100.0   2009.0
1     Luxembourg *      Western Europe  Europe  ...  2020.0  114482.0   2019.0
2         Monaco *      Western Europe  Europe  ...     NaN  115700.0   2015.0
3      Singapore *  South-eastern Asia    Asia  ...  2020.0   97341.0   2019.0
4        Ireland *     Northern Europe  Europe  ...  2020.0   86781.0   2019.0

[5 rows x 9 columns]

`pandas` DataFrame sorting

In [ ]:
df.sort_values(by='CIA',ascending=False)

                        country           subregion  ...       CIA  CIAyear
0               Liechtenstein *      Western Europe  ...  139100.0   2009.0
6                       Macau *        Eastern Asia  ...  123965.0   2019.0
2                      Monaco *      Western Europe  ...  115700.0   2015.0
1                  Luxembourg *      Western Europe  ...  114482.0   2019.0
3                   Singapore *  South-eastern Asia  ...   97341.0   2019.0
..                          ...                 ...  ...       ...      ...
223                  DR Congo *       Middle Africa  ...    1098.0   2019.0
222                    Malawi *      Eastern Africa  ...    1060.0   2019.0
224  Central African Republic *       Middle Africa  ...     945.0   2019.0
226                   Burundi *      Eastern Africa  ...     752.0   2019.0
225                   Somalia *      Eastern Africa  ...       NaN      NaN

[227 rows x 9 columns]

In [ ]:
df['country'].str.replace('*','A').str.replace('n','XSDSF')

0                 LiechteXSDSFsteiXSDSF A
1                            Luxembourg A
2                            MoXSDSFaco A
3                         SiXSDSFgapore A
4                           IrelaXSDSFd A
                      ...
222                              Malawi A
223                        DR CoXSDSFgo A
224    CeXSDSFtral AfricaXSDSF Republic A
225                             Somalia A
226                         BuruXSDSFdi A
Name: country, Length: 227, dtype: object

In [ ]:
df=df.sort_values(by='country')
df['country']=df['country'].str.replace('*','')

In [ ]:
df.to_csv('my_data.csv')

# Scraping *level 2*

In [ ]:
url='https://www.comparethemarket.com/car-insurance/content/global-supercar-index/'

In [ ]:
pd.read_html(url)

HTTPError: ignored

In [187]:
from bs4 import BeautifulSoup

In [188]:
html = requests.get(url)
soup = BeautifulSoup(html.content, 'html.parser')

In [190]:
divs=soup.findAll('div')

In [195]:
table=soup.find('div',id='cheapest-countries')

In [198]:
headings=table.findAll('h4')

In [203]:
values=table.findAll('p',class_='lead')
# table.findAll('p',{'class':'lead'})

In [212]:
[i.text for i in headings]

['Canada', 'Mexico', 'United Kingdom']

In [ ]:
headings_list=[i.text for i in headings]

In [219]:
values_list=[i.text.replace('£','').replace(',','') for i in values]

In [220]:
headings_list

['Canada', 'Mexico', 'United Kingdom']

In [221]:
values_list

['136703', '139930', '155970']

In [224]:
pd.DataFrame([headings_list,values_list]).T

                0       1
0          Canada  136703
1          Mexico  139930
2  United Kingdom  155970

In [ ]:
df1=pd.DataFrame([headings_list,values_list]).T

In [ ]:
table=soup.find('div',id='expensive-countries')
headings=table.findAll('h4')
values=table.findAll('p',class_='lead')
df2=pd.DataFrame([[i.text for i in headings],
              [int(i.text.replace('£','').replace(',','')) for i in values]]).T

In [ ]:
pd.concat([df1,df2])

                0       1
0          Canada  136703
1          Mexico  139930
2  United Kingdom  155970
0       Argentina  549840
1       Singapore  526958
2         Vietnam  524620

# Advanced: scraping with `Selenium` *zombie browser*